### ISSUE TITLE
Cant deposit a single item

### ISSUE THREAD

**Issue by wireva** [Tmanyo/bank_accounts#2]
When you try to put a single minegeld note in the deposit field, it goes back.

**Comment by ApolloX939** [comment]
I have encountered the same issue... (A simple workaround if it's a single $10 mg... just split it into 2 $5 mg notes)

I have yet to look at the code... just wanted to look and see where the project was at currently before I start working on fix it up.

(Even if that means I fix it and then there is a code update where it gets refactored/cleaned up)

**Comment by ApolloX939** [comment]
Looks like there is code in there to prevent depositing a single item... why though?

I.E. I have a single (1) 10 mg note, the ATM will stop me dead in my track until I get another 10 mg note!?! Why?

Ok so it's to attempt to prevent you from loosing your money... wow... ok well let's see if I can't refactor it so it won't do that but still allow a single item to be deposited.

**Comment by Tmanyo** [comment]
This merge from Beanzilla should resolve this issue.
